language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  include:
  - php: 5.6
    env: COMPOSER_FLAGS="--prefer-lowest"
  - php: 5.6
    env: DEPENDENCIES="symfony/lts:^2"
  - php: 7.1
    env: DEPENDENCIES="symfony/lts:^3"

sudo: false

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --prefer-dist $COMPOSER_FLAGS
  - if [ "$DEPENDENCIES" != "" ]; then composer require --no-update $DEPENDENCIES; fi;

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
